--liquibase formatted sql

--changeset pisklov:2024-11-14-001-table-account_aud
create table account_aud
(
    id                 bigserial,
    rev                integer  not null,
    created_date       timestamp,
    last_modified_date timestamp,
    name               varchar(255),
    surname            varchar(255),
    login              varchar(255),
    mail               varchar(255),
    revtype            smallint not null,
    primary key (id, rev)
);

--changeset pisklov:2024-11-14-002-table-account_book_aud
create table account_book_aud
(
    id                 bigserial,
    rev                integer  not null,
    created_date       timestamp,
    last_modified_date timestamp,
    account_id         integer,
    book_id            integer,
    revtype            smallint not null,
    primary key (id, rev)
);

--changeset pisklov:2024-11-14-003-table-revinfo
create table revinfo
(
    rev      integer generated by default as identity (start with 1) not null,
    revtstmp bigint,
    primary key (rev)
);

--changeset pisklov:2024-11-14-004-account_aud-foreign_key
alter table account_aud
    add foreign key (rev) references revinfo (rev);

--changeset pisklov:2024-11-14-005-account_book_aud-foreign_key
alter table account_book_aud
    add foreign key (rev) references revinfo (rev);

--changeset pisklov:2024-11-14-006-sequence-revinfo_seq
CREATE SEQUENCE revinfo_seq INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;