version: "3.9"
services:

  postgres_library:
    image: postgres:13.3
    container_name: library-service-db
    environment:
      POSTGRES_DB: "library-service-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata_library:/var/lib/postgresql/data
    networks:
      monitoring:
        aliases:
          - postgres

  postgres_order:
    image: postgres:13.3
    container_name: order-service-db
    environment:
      POSTGRES_DB: "order-service-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata_order:/var/lib/postgresql/data
    networks:
      monitoring:
        aliases:
          - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring:
    name: hw-networks