application:
  orderUrlBase: http://localhost:8001

server:
  port: 8000

spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5433/library-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
  #    refresh:
  #      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env' ]
    enabled-by-default: false
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiter:
        limit-for-period: 5
        limit-refresh-period: 30s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50