application:
  orderUrlBase: http://localhost:8001

server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env' ]
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace