application:
  libraryUrlBase: ${LIBRARY-SERVICE:http://localhost:8000}
#  orderUrlBase:  ${ORDER-SERVICE:http://localhost:8001}
  orderUrlBase: ORDER-SERVICE

server:
  port: 8002

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5435/account-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
  instance:
    instance-id: account-service:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh' ]
    enabled-by-default: false

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 10
    instances:
      circuitBreakerOrderRestClient:
        baseConfig: default
        waitDurationInOpenState: 20s
      circuitBreakerLibraryRestClient:
        baseConfig: default
        waitDurationInOpenState: 20s