spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: mongo_db
      port: 27017
      host: localhost

server:
  port: 8080

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local