--liquibase formatted sql

--changeset pisklov:2024-11-13-001-table-book_order_aud
create table book_order_aud
(
    id                 bigserial,
    rev                integer   not null,
    created_date       timestamp not null,
    last_modified_date timestamp,
    login              varchar(255),
    book_title         varchar(255),
    status             varchar(55),
    revtype            smallint,
    primary key (id, rev)
);

--changeset pisklov:2024-11-13-002-table-revinfo
create table revinfo
(
    rev      integer generated by default as identity (start with 1) not null,
    revtstmp bigint,
    primary key (rev)
);

--changeset pisklov:2024-11-13-003-book_order_aud-foreign key
alter table book_order_aud
    add foreign key (rev) references revinfo (rev);

--changeset pisklov:2024-11-13-004-sequence-revinfo_seq
CREATE SEQUENCE revinfo_seq INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;