### Получить список книг
GET http://localhost:8080/api/v1/book

### Получить список авторов
GET http://localhost:8080/api/v1/author

### Получить список жанров
GET http://localhost:8080/api/v1/genre

### Получить книгу по ID
GET http://localhost:8080/api/v1/book/674a15a857f29e09f9a156f4

### Создать книгу
POST http://localhost:8080/api/v1/book
Content-Type: application/json

{
    "title": "test",
    "author": {
      "id": "674a0fb76238900cefffab06"
    },
    "genres": [
      {
        "id": "674a0fb76238900cefffab0c"
      }
    ]
  }

### Обновить книгу
PUT http://localhost:8080/api/v1/book
Content-Type: application/json

{
  "id": "674a0fb76238900cefffab10",
  "title": "test",
  "author": {
    "id": "674a0fb76238900cefffab06"
  },
  "genres": [
    {
      "id": "674a0fb76238900cefffab0c"
    }
  ]
}

### Удалить книгу
DELETE http://localhost:8080/api/v1/book/674a15a857f29e09f9a156f4