### Получить список книг (api)
GET http://localhost:8080/api/v1/book

### Получить список авторов (api)
GET http://localhost:8080/api/v1/author

### Получить список жанров (api)
GET http://localhost:8080/api/v1/genre

### Получить книгу по ID (route)
GET http://localhost:8080/route/v1/book/675cda0a9b75f0244c6b4a4f

### Создать книгу (api)
POST http://localhost:8080/api/v1/book
Content-Type: application/json

{
  "title": "Manual creation of a book",
  "authorId": "674ae65473aec45d9f703b14",
  "genresId": [
    "674ae65473aec45d9f703b16"
  ]
}

### Создать книгу (route)
POST http://localhost:8080/route/v1/book
Content-Type: application/json

{
  "title": "Manual creation of a book (route)",
  "authorId": "675cd77f82389e16e28566d2",
  "genresId": [
    "675cd77f82389e16e28566d9"
  ]
}

### Обновить книгу (api)
PUT http://localhost:8080/api/v1/book
Content-Type: application/json

{
  "id": "675cd77f82389e16e28566de",
  "title": "Manual book update",
  "authorId": "675cd77f82389e16e28566d3",
  "genresId": [
    "675cd77f82389e16e28566da"
  ]
}

### Обновить книгу (route)
PUT http://localhost:8080/route/v1/book
Content-Type: application/json

{
  "id": "675cdc6d9edb5b3cf925b832",
  "title": "Manual book update",
  "authorId": "675cdc6d9edb5b3cf925b825",
  "genresId": [
    "675cdc6d9edb5b3cf925b82c"
  ]
}

### Удалить книгу (api)
DELETE http://localhost:8080/api/v1/book/674afb826163c11ec0cc13e1

### Удалить книгу (route)
DELETE http://localhost:8080/route/v1/book/675cd196adcf9e3c80fe5d54