application:
  services:
    orderUrl: lb://ORDER-SERVICE
    accountUrl: lb://ACCOUNT-SERVICE
  security:
    enabled: ${SECURITY_ENABLED:false}

server:
  port: 8000

spring:
  application:
    name: library-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/library-service-db}
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_PROVIDER_URL:http://localhost:9000}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
  instance:
    instance-id: account-service:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      refresh:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh' ]
    enabled-by-default: false
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 10
    instances:
      circuitBreakerAccountRestClient:
        baseConfig: default
        waitDurationInOpenState: 20s
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterAuthor:
        limit-for-period: 5
        limit-refresh-period: 30s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50
      rateLimiterGenre:
        limit-for-period: 5
        limit-refresh-period: 30s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50