scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000',
                  'host.docker.internal:8001',
                  'host.docker.internal:8002',
                  'host.docker.internal:8003',
                  'host.docker.internal:8080']