spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh' ]
    enabled-by-default: false
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_URL:localhost:9411}/api/v2/spans