--liquibase formatted sql

--changeset pisklov:2024-11-18-001-table-raw_message_aud
create table raw_message_aud
(
    id                   bigserial,
    rev                  integer  not null,
    created_date         timestamp,
    last_modified_date   timestamp,
    login                varchar(255),
    content              text,
    external_system_name varchar(255),
    message_type         varchar(55),
    status               varchar(55),
    revtype              smallint not null,
    primary key (id, rev)
);

--changeset pisklov:2024-11-18-002-table-message_to_user_aud
create table message_to_user_aud
(
    id                 bigserial,
    rev                integer  not null,
    created_date       timestamp,
    last_modified_date timestamp,
    login              varchar(255),
    mail               varchar(255),
    message            text,
    status             varchar(55),
    revtype            smallint not null,
    primary key (id, rev)
);

--changeset pisklov:2024-11-18-003-table-revinfo
create table revinfo
(
    rev      integer generated by default as identity (start with 1) not null,
    revtstmp bigint,
    primary key (rev)
);

--changeset pisklov:2024-11-18-004-raw_message_aud-foreign_key
alter table raw_message_aud
    add foreign key (rev) references revinfo (rev);

--changeset pisklov:2024-11-18-005-message_to_user_aud-foreign_key
alter table message_to_user_aud
    add foreign key (rev) references revinfo (rev);

--changeset pisklov:2024-11-18-006-sequence-revinfo_seq
CREATE SEQUENCE revinfo_seq INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;