spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: mongo_db
      port: 27017
      host: localhost

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local