application:
  accountUrlBase: http://ACCOUNT-SERVICE
  scheduler:
    enabled: true

server:
  port: 8003

spring:
  application:
    name: notification-service
  datasource:
    hikari:
#      transaction-isolation: TRANSACTION_READ_COMMITTED # TRANSACTION_READ_COMMITTED / TRANSACTION_REPEATABLE_READ / TRANSACTION_SERIALIZABLE
      maximum-pool-size: 10
      minimum-idle: 1
    url: jdbc:postgresql://localhost:5436/notification-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
  instance:
    instance-id: notification-service:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh' ]
    enabled-by-default: false

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 10
    instances:
      circuitBreakerAccountRestClient:
        baseConfig: default
        waitDurationInOpenState: 20s
