application:
  services:
    libraryUrl: lb://LIBRARY-SERVICE
  security:
    enabled: ${SECURITY_ENABLED:false}

server:
  port: 8001

spring:
  application:
    name: order-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5434/order-service-db}
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_PROVIDER_URL:http://localhost:9000}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
  instance:
    instance-id: order-service:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh', 'info']
    enabled-by-default: false

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  retry:
    metrics:
      enabled: true
      legacy:
        enabled: true
    instances:
      retryCacheScheduled:
        max-attempts: 4
        wait-duration: 2s
