application:
  services:
    libraryUrl: lb://LIBRARY-SERVICE
  security:
    enabled: ${SECURITY_ENABLED:false}

server:
  port: 8001

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL:localhost:5434}/order-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: ${CLOUD_CONFIG_ENABLE:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_URL:localhost:8888}/realms/project

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_URL:localhost:8761}/eureka
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: order-service:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh', 'info']
    enabled-by-default: false
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_URL:localhost:9411}/api/v2/spans

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace

resilience4j:
  retry:
    metrics:
      enabled: true
      legacy:
        enabled: true
    instances:
      retryCacheScheduled:
        max-attempts: 4
        wait-duration: 2s
