GET http://localhost:8001/order-service/api/v1/order

###
GET http://localhost:8001/order-service/api/v1/order/guest

###
POST http://localhost:8001/order-service/api/v1/order
Content-Type: application/json

{
    "login": "user_request",
    "bookTitle": "The Three-Body Problem"
  }

###
PUT http://localhost:8001/order-service/api/v1/order
Content-Type: application/json

{
  "id": 1,
  "login": "user_request",
  "bookTitle": "Dune",
  "status": "CREATED"
}
