GET http://localhost:8001/api/v1/order

###
GET http://localhost:8001/api/v1/order/guest

###
POST http://localhost:8001/api/v1/order
Content-Type: application/json

{
    "login": "guest",
    "bookTitle": "The Three-Body Problem"
  }

###
PUT http://localhost:8001/api/v1/order
Content-Type: application/json

{
  "id": 1,
  "login": "guest",
  "bookTitle": "Dune",
  "status": "WAIT"
}
