spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false

server:
  port: 8080

application:
  api-routes:
    - id: order-service
      from: api/v1/order
      to: lb://ORDER-SERVICE
    - id: account-service
      from: api/v1/account
      to: lb://ACCOUNT-SERVICE
    - id: notification-service
      from: /api/v1/user-message
      to: lb://NOTIFICATION-SERVICE
    - id: library-service
      from: /api/v1/book
      to: lb://LIBRARY-SERVICE

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env', 'refresh' ]
    enabled-by-default: false

logging:
  level:
    root: debug