application:
  libraryUrlBase: http://localhost:8000
  scheduler:
    enabled: true

server:
  port: 8001

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order-service-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
#    refresh:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus', 'git', 'env' ]
    enabled-by-default: false

logging:
  level:
    '[root]': info
    '[http]': info
    '[com.zaxxer.hikari]': trace