version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo

  #admin:pass
  mongo-express:
    ports:
      - '8081:8081'
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/
    image: mongo-express